/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as ApiRoomsRoomIdSocketRouteImport } from './routes/api/rooms/$roomId/socket'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsRoomIdSocketRoute = ApiRoomsRoomIdSocketRouteImport.update({
  id: '/api/rooms/$roomId/socket',
  path: '/api/rooms/$roomId/socket',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/api/rooms/$roomId/socket': typeof ApiRoomsRoomIdSocketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/api/rooms/$roomId/socket': typeof ApiRoomsRoomIdSocketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/api/rooms/$roomId/socket': typeof ApiRoomsRoomIdSocketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/room/$roomId' | '/api/rooms/$roomId/socket'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/room/$roomId' | '/api/rooms/$roomId/socket'
  id: '__root__' | '/' | '/room/$roomId' | '/api/rooms/$roomId/socket'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  ApiRoomsRoomIdSocketRoute: typeof ApiRoomsRoomIdSocketRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$roomId/socket': {
      id: '/api/rooms/$roomId/socket'
      path: '/api/rooms/$roomId/socket'
      fullPath: '/api/rooms/$roomId/socket'
      preLoaderRoute: typeof ApiRoomsRoomIdSocketRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  ApiRoomsRoomIdSocketRoute: ApiRoomsRoomIdSocketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
